In [177]:
import numpy as np

In [18]:
a = np.arange(12, 24)

In [30]:
a.reshape(2, 6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [31]:
a.reshape(3, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [33]:
a.reshape(4,3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [34]:
a.reshape(6,2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [38]:
a.reshape(12, 1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [40]:
np.reshape(a, (6, -1))

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [42]:
np.reshape(a, (4, -1))

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [43]:
np.reshape(a, (3, -1))

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [44]:
np.reshape(a, (2, -1))

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [45]:
np.reshape(a, (-1, 2))

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [48]:
np.reshape(a, (-1, 1)).shape

(12, 1)

Такой массив нельзя назвать одномерным для Numpy, т.к каждая строка это отдельный массив в общем массиве. Массив с одним столбцом можно транспонировать, а с одной строкой нельзя.

In [54]:
newarr = np.random.randn(3, 4)
newarr

array([[ 1.41278871, -0.21714164, -0.35687398,  0.66752429],
       [ 0.79780815,  0.72938741,  0.19997684,  2.46887789],
       [ 0.17477345,  0.08966145, -1.23400668, -0.2025093 ]])

In [57]:
newarr1 = newarr.flatten()

In [58]:
newarr1.size == newarr.size

True

In [93]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [78]:
b = np.arange(20, 1, -2).reshape(10,1)
b

array([[20],
       [18],
       [16],
       [14],
       [12],
       [10],
       [ 8],
       [ 6],
       [ 4],
       [ 2]])

Массив a - одномерный и горизонтальный, массив b - вертикальный и двумерный.

In [198]:
b = np.ones((3, 2))
a = np.zeros((2, 2)) 

In [199]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [200]:
v.size

10

In [114]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [115]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [116]:
At = A.transpose()
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [111]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [117]:
np.linalg.inv(B)

LinAlgError: Singular matrix

In [119]:
np.linalg.det(B)

0.0

Матрица B - вырожденная (ее определитель равен нулю), поэтому для нее нельзя получить обратную матрицу

In [120]:
np.random.seed(42)

In [154]:
c = np.random.randint(0, 16, 16)
c

array([ 3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4,  3])

In [155]:
row_number = int(np.sqrt(int(c.size)))

In [156]:
C = np.reshape(c, (row_number, -1))
C

array([[ 3, 12, 14, 10],
       [ 7, 12,  4,  6],
       [ 9,  2,  6, 10],
       [10,  7,  4,  3]])

In [157]:
D = B + C * 10
D

array([[ 35, 134, 163, 132],
       [ 84, 170, 126, 182],
       [113, 106, 209, 312],
       [132, 192, 252, 332]])

In [158]:
np.linalg.det(D)

21320000.000000034

In [159]:
np.linalg.matrix_rank(D)

4

In [165]:
D_inv = np.linalg.inv(D)
D_inv

array([[-0.0421257 , -0.04781989, -0.07423077,  0.11272233],
       [ 0.00713133,  0.01837899,  0.00807692, -0.02050094],
       [-0.00235084, -0.03018386, -0.02807692,  0.04386679],
       [ 0.01440901,  0.03129456,  0.04615385, -0.06324578]])

In [166]:
D_inv[D_inv > 0] = 1
D_inv[D_inv < 0] = 0
D_inv

array([[0., 0., 0., 1.],
       [1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [1., 1., 1., 0.]])

In [169]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [172]:
C

array([[ 3, 12, 14, 10],
       [ 7, 12,  4,  6],
       [ 9,  2,  6, 10],
       [10,  7,  4,  3]])

In [175]:
E = np.where(D_inv, C, B)
E

array([[  5,  14,  23,  10],
       [  7,  12,   4, 122],
       [ 23,  86, 149,  10],
       [ 10,   7,   4, 302]])